sudo: false

language: php
dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  - composer
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_TRAVISCI=phpcs
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.3
      env: WP_VERSION=latest

script:
  - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi 2>&1
